config/routes.rb
Rails.application.routes.draw do
  resources :messages, :only => [:index, :new, :create, :show]
  resources :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_sms

private

  def send_sms
    begin
    response = RestClient::Request.new(
      :method => :post,
      :verify_ssl => false,
      :url => 'https://api.twilio.com/2010-04-01/Accounts/AC5abfc69a8e719b4a456a7e7858a56fec/Messages.json',
      :user => ENV['TWILIO_ACCOUNT_SID'],
      :password => ENV['TWILIO_AUTH_TOKEN'],
      :payload => { :Body => body,
                    :From => from,
                    :To => to }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

# response = RestClient::Request.new(
# :method => :post,
# :verify_ssl => false,
# :url => 'https://api.twilio.com/2010-04-01/Accounts/AC5abfc69a8e719b4a456a7e7858a56fec/Messages.json',
# :user => 'AC5abfc69a8e719b4a456a7e7858a56fec',
# :password => 'eab68a0e46846e0834d2e47fc8f093fe',
# :payload => { :Body => "body",
#   :From => 4802073339,
#   :To => 6024890731 && 6024890731 }
#   ).execute

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:notice] = "Contact Added!"
      redirect_to messages_path
    else
      redirect_to messages_path
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :number, :id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def index
    @messages = Message.all
    @contacts = Contact.all
    @contact = Contact.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Message sent!"
      redirect_to messages_path
    else
      render 'new'
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  private

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/show.html.erb
<br><h3><%= @contact.name %>'s Number: <%= @contact.number %><h3>

  <br><h4>Send a message to <%= @contact.name %></h4>

<%= form_for Message.new do |f| %>
  <%= f.text_field(:to, value: @contact.number, type: "hidden") %>
  <%= f.label :from %>
  <%= f.text_field :from %><br>
  <%= f.label :body %><br>
  <%= f.text_area(:body, size: "30x2") %><br>
  <button class="btn btn-xs btn-primary">Send</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Texter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <div class="container">
    <body>
        <h1><small><%= link_to "Create New Message", new_message_path %></small></h1>
      <div class="nav">
        <button class="btn btn-primary btn-xs"><%= link_to 'Home', "/messages" %></button>
      </div>
<%= flash[:notice] %>
<%= yield %>
  </div>
</body>
</html>

app/views/messages/index.html.erb
<h1>Sent Messages</h1>


  <% @messages.each do |message| %>
  <h4>"<%= link_to message.body, message_path(message) %>"</h4>
  <% end %>


<!-- select
optionvalue = "person.name"
optionvalue = "person.name"
optionvalue = "person.name"
/select

value= selected person.email -->

<div class="column">
  <h1>Saved Contacts <small>Click to send a message</small></h1>
  <% if @contacts %>
    <% @contacts.each do |contact| %>
      <h4><%= link_to contact.name, contact_path(contact) %>'s number: <%= contact.number %></h4>
      <% end %>
    <% end %>

  <%= form_for @contact do |f| %>
    <%= f.label :Name %>
    <%= f.text_field :name %>
    <%= f.label :Number %>
    <%= f.text_field :number %><br>
    <button class="btn btn-xs btn-primary">Add</button>
  <% end %>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
  <p>Error:</p>
  <% @message.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

  <button id="add" class="btn btn-xs btn-primary">Add another number</button><br>

<%= form_for @message do |f| %>
  <div id="new-number"></div>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :to %>
  <%= f.text_field :to %><br>
  <%= f.label :body %><br>
  <%= f.text_area(:body, size: "30x2") %><br>
  <button class="btn btn-xs btn-primary">Send</button>
<% end %>

app/views/messages/show.html.erb
<br>
<h3>"<%= @message.body %>"</h3> <h4><br>Sent to: <%= @message.to %>
<br><br>From: <%= @message.from %></h4>